# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
julia:
  - 1.0
  - 1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

env:
  - CGBITMAP_CONTEXT_LOG_ERRORS=1

after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("QuartzImageIO")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
